name: CI-petsc-benchmarks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pytest:
    name: ${{ matrix.name }}-${{ matrix.set }}
    runs-on: "${{ matrix.os }}"

    env:
      DOCKER_BUILDKIT: "1"
      DEVITO_ARCH: "${{ matrix.arch }}"
      DEVITO_LANGUAGE: ${{ matrix.language }}

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
           pytest-docker-py39-gcc-noomp
        ]
        include:
        - name: pytest-docker-py39-gcc-noomp
          python-version: '3.9'
          os: ubuntu-latest
          arch: "gcc"
          language: "C"
          sympy: "1.12"

    steps:
    - name: Checkout Devito-PETSc-Benchmarks
      uses: actions/checkout@v4

    - name: Pull pre-built Docker image
      run: |
          docker pull zoeleibowitz/devito_img:latest

    - name: Set run prefix
      run: |
          echo "RUN_CMD=docker run --rm -t -v $(pwd)/tests:/app/tests -v $(pwd)/examples:/app/examples -w /app -e --name zoeleibowitz/devito_img:latest"  >> $GITHUB_ENV

    - name: Check configuration
      run: |
        ${{ env.RUN_CMD }} python3 -c "from devito import configuration; print(''.join(['%s: %s \n' % (k, v) for (k, v) in configuration.items()]))"

    - name: Run tests
      run: |
        ${{ env.RUN_CMD }} python3 -m pytest tests/test_petsc2.py
  
    # - name: Examples
    #   run: |
    #     ${{ env.RUN_CMD }} mpiexec -n 1 python3 examples/Helmholtz/helmholtz.py
